// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: sdk/rpc/testpb/service.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Large         int64                  `protobuf:"varint,1,opt,name=large,proto3" json:"large,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_sdk_rpc_testpb_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_rpc_testpb_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_sdk_rpc_testpb_service_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetLarge() int64 {
	if x != nil {
		return x.Large
	}
	return 0
}

func (x *Request) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Request) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Request) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Request) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      *Request               `protobuf:"bytes,1,opt,name=received,proto3" json:"received,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_sdk_rpc_testpb_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_rpc_testpb_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_sdk_rpc_testpb_service_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetReceived() *Request {
	if x != nil {
		return x.Received
	}
	return nil
}

func (x *Reply) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

var File_sdk_rpc_testpb_service_proto protoreflect.FileDescriptor

const file_sdk_rpc_testpb_service_proto_rawDesc = "" +
	"\n" +
	"\x1csdk/rpc/testpb/service.proto\x12\arpctest\"w\n" +
	"\aRequest\x12\x14\n" +
	"\x05large\x18\x01 \x01(\x03R\x05large\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"I\n" +
	"\x05Reply\x12,\n" +
	"\breceived\x18\x01 \x01(\v2\x10.rpctest.RequestR\breceived\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node27\n" +
	"\vApplication\x12(\n" +
	"\x04Echo\x12\x10.rpctest.Request\x1a\x0e.rpctest.Reply24\n" +
	"\bInternal\x12(\n" +
	"\x04Echo\x12\x10.rpctest.Request\x1a\x0e.rpctest.ReplyB\x18Z\x16distvis/sdk/rpc/testpbb\x06proto3"

var (
	file_sdk_rpc_testpb_service_proto_rawDescOnce sync.Once
	file_sdk_rpc_testpb_service_proto_rawDescData []byte
)

func file_sdk_rpc_testpb_service_proto_rawDescGZIP() []byte {
	file_sdk_rpc_testpb_service_proto_rawDescOnce.Do(func() {
		file_sdk_rpc_testpb_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_rpc_testpb_service_proto_rawDesc), len(file_sdk_rpc_testpb_service_proto_rawDesc)))
	})
	return file_sdk_rpc_testpb_service_proto_rawDescData
}

var file_sdk_rpc_testpb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_rpc_testpb_service_proto_goTypes = []any{
	(*Request)(nil), // 0: rpctest.Request
	(*Reply)(nil),   // 1: rpctest.Reply
}
var file_sdk_rpc_testpb_service_proto_depIdxs = []int32{
	0, // 0: rpctest.Reply.received:type_name -> rpctest.Request
	0, // 1: rpctest.Application.Echo:input_type -> rpctest.Request
	0, // 2: rpctest.Internal.Echo:input_type -> rpctest.Request
	1, // 3: rpctest.Application.Echo:output_type -> rpctest.Reply
	1, // 4: rpctest.Internal.Echo:output_type -> rpctest.Reply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sdk_rpc_testpb_service_proto_init() }
func file_sdk_rpc_testpb_service_proto_init() {
	if File_sdk_rpc_testpb_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_rpc_testpb_service_proto_rawDesc), len(file_sdk_rpc_testpb_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sdk_rpc_testpb_service_proto_goTypes,
		DependencyIndexes: file_sdk_rpc_testpb_service_proto_depIdxs,
		MessageInfos:      file_sdk_rpc_testpb_service_proto_msgTypes,
	}.Build()
	File_sdk_rpc_testpb_service_proto = out.File
	file_sdk_rpc_testpb_service_proto_goTypes = nil
	file_sdk_rpc_testpb_service_proto_depIdxs = nil
}
