// Optional real-browser acceptance. Run against an idle local coordinator.
const { chromium } = await import(process.env.DISTVIS_PLAYWRIGHT_MODULE || 'playwright');
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true, ...(process.env.DISTVIS_BROWSER_PATH ? { executablePath: process.env.DISTVIS_BROWSER_PATH } : {}) });
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 1 });
const errors = [];
await page.setExtraHTTPHeaders({'X-Distvis-Purpose':'acceptance'});
page.on('pageerror', e => errors.push(e.message));
try {
  await page.goto(process.env.DISTVIS_URL || 'http://localhost:3000');
  await page.locator('#create-experiment').click();
  await page.locator('#project-form [name="name"]').fill('浏览器验收 · Raft 工作区');
  await page.locator('#project-form [type="submit"]').click();
  await page.locator('#workspace-title').filter({hasText:'浏览器验收 · Raft 工作区'}).waitFor();
  await page.locator('#workspace-new-experiment').click();
  await page.locator('#new-form [name="name"]').fill('独立参数实验');
  await page.locator('#run-submit').click();
  await page.locator('#breadcrumb-experiment').filter({hasText:'独立参数实验'}).waitFor();
  await page.locator('#new-run').click();
  await page.locator('#new-dialog[open]').waitFor();
  await page.locator('#new-form [name="name"]').fill('浏览器验收 · Raft');
  await page.locator('#new-form [name="runtime"]').selectOption('simulation');
  await page.locator('#new-form [type="submit"]').click();
  await page.locator('#run-status').filter({ hasText: '运行中' }).waitFor();
  await page.waitForFunction(() => document.querySelectorAll('.graph-node').length === 5);
  await page.waitForFunction(() => [...document.querySelectorAll('.node-role')].some(n => n.textContent.includes('LEADER')));
  await page.locator('#graph [data-node="node-1"]').click();
  await page.locator('#application-panel input[name="number"]').fill('42');
  await page.locator('#application-panel button[type="submit"]').click();
  await page.waitForFunction(() => document.querySelector('#node-panel [data-field="lastProposal"]')?.textContent.includes('Leader 已接收'));
  assert.equal(await page.locator('#application-panel input[name="number"]').inputValue(), '42', 'state updates preserve input draft');
  await mkdir('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
  await page.locator('#play').click();
  await page.locator('#rewind').click();
  assert.equal(await page.locator('#event-count').textContent(), '0');
  await page.locator('#step').click();
  assert.equal(await page.locator('#event-count').textContent(), '1');
  await page.locator('#go-live').click();
  // One click selects the target, one click injects the fault.
  await page.locator('#graph [data-node="node-1"]').click();
  await page.locator('#node-toggle[data-node-action="crash"]').click();
  await page.waitForFunction(() => document.querySelectorAll('.node-offline').length === 1);
  await page.locator('#node-toggle[data-node-action="recover"]').click();
  await page.waitForFunction(() => document.querySelectorAll('.node-offline').length === 0);
  await page.locator('#stop-run').click();
  await page.locator('#run-status').filter({ hasText: '已结束' }).waitFor();
  assert.equal(await page.locator('#application-panel button[type="submit"]').isDisabled(), true);
  await page.locator('[data-view="spacetime"]').click();
  assert.equal(await page.locator('#graph').isVisible(), false, 'time-space view replaces the topology');
  await page.locator('.time-message').first().waitFor();
  const lanes = await page.locator('[data-lane]').evaluateAll(lines => lines.map(line => ({
    x1: Number(line.getAttribute('x1')), x2: Number(line.getAttribute('x2')),
    y1: Number(line.getAttribute('y1')), y2: Number(line.getAttribute('y2'))
  })));
  assert.equal(lanes.length, 5);
  assert.ok(lanes.every((lane, i) => lane.x2 > lane.x1 && lane.y1 === lane.y2 && (!i || lane.y1 > lanes[i - 1].y1)), 'each node has a separate horizontal lane');
  const replayPosition = await page.locator('#event-count').textContent();
  const startAt = () => page.locator('#spacetime').getAttribute('data-start').then(Number);
  const followingStart = await startAt();
  assert.ok(followingStart > 0, 'recording extends beyond the default window');
  const canvas = page.locator('.spacetime-scroll');
  await canvas.scrollIntoViewIfNeeded();
  const box = await canvas.boundingBox();
  await page.mouse.move(box.x + box.width * 0.5, box.y + 240);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width * 0.75, box.y + 240, { steps: 8 });
  await page.mouse.up();
  assert.ok(await startAt() < followingStart, 'dragging right reveals earlier time');
  assert.equal(await page.locator('#spacetime-follow').getAttribute('aria-pressed'), 'false');
  assert.equal(await page.locator('#event-dialog').getAttribute('open'), null, 'dragging does not inspect a packet');
  assert.equal(await page.locator('#event-count').textContent(), replayPosition, 'panning preserves the replay cursor');
  const pannedStart = await startAt();
  await canvas.focus();
  await page.keyboard.press('ArrowRight');
  assert.ok(await startAt() > pannedStart, 'keyboard pans forward');
  await page.locator('#spacetime-window').selectOption('100');
  assert.equal(Number(await page.locator('#spacetime').getAttribute('data-end')) - await startAt(), 100);
  await page.locator('#spacetime-window').selectOption('1000');
  await page.locator('#spacetime-follow').click();
  assert.equal(await startAt(), followingStart, 'follow restores the playback position');
  await page.locator('#spacetime-options > summary').click();
  await page.locator('#spacetime-node').selectOption('node-1');
  assert.ok((await page.locator('.time-message').evaluateAll(groups => groups.map(g => g.getAttribute('aria-label')))).every(label => label.split(' · ')[0].includes('node-1')));
  await page.locator('#spacetime-node').selectOption('all');
  await page.locator('#spacetime-heartbeats').check();
  assert.ok((await page.locator('.time-message').evaluateAll(groups => groups.map(g => g.textContent))).every(text => !text.includes('Heartbeat')));
  await page.locator('#spacetime-heartbeats').uncheck();
  await page.screenshot({ path: 'artifacts/spacetime.png', fullPage: true });
  await page.locator('.time-message').first().focus();
  await page.keyboard.press('Enter');
  await page.locator('#event-dialog[open]').waitFor();
  assert.equal(await page.locator('#event-title').textContent(), '消息详情');
  assert.ok((await page.locator('#event-summary .message-route').textContent()).includes('→'));
  assert.ok(await page.locator('#event-summary .payload-field').count());
  await page.locator('#event-dialog .close-dialog').click();
  await page.locator('#spacetime [data-node="node-1"]').click();
  assert.ok(await page.locator('#node-panel [data-field="term"]').count());
  await page.locator('#nav-history').click();
  await page.locator('.history-row').filter({ hasText: '浏览器验收 · Raft' }).first().locator('[data-history]').click();
  await page.locator('#visual-panel').waitFor();
  assert.equal(await page.locator('#event-count').textContent(), '0');
  await page.locator('#play').click();
  await page.waitForFunction(() => Number(document.querySelector('#event-count').textContent.replaceAll(',', '')) > 1);
  await page.locator('#speed').selectOption('0.01');
  await page.locator('#play').click();
  await page.locator('#rewind').click();
  await page.locator('#play').click();
  const before = await page.locator('#timecode').textContent();
  await page.waitForTimeout(1000);
  const after = await page.locator('#timecode').textContent();
  assert.notEqual(before, after, 'slow playback advances');
  assert.ok(Number(after.split('.')[1]) < 30, 'one wall second advances only about 10ms');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.deepEqual(errors, []);
  console.log('Browser acceptance passed: horizontal node lanes, drag/keyboard pan, zoom, follow, filters, replay and mobile layout. Screenshots: artifacts/desktop.png, artifacts/spacetime.png, artifacts/mobile.png');
} finally {
  await browser.close();
}
