// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: api/protocol.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberRequest) Reset() {
	*x = NumberRequest{}
	mi := &file_api_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberRequest) ProtoMessage() {}

func (x *NumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberRequest.ProtoReflect.Descriptor instead.
func (*NumberRequest) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *NumberRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *NumberRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type NumberReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Number        int64                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberReply) Reset() {
	*x = NumberReply{}
	mi := &file_api_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberReply) ProtoMessage() {}

func (x *NumberReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberReply.ProtoReflect.Descriptor instead.
func (*NumberReply) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *NumberReply) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *NumberReply) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *NumberReply) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

var File_api_protocol_proto protoreflect.FileDescriptor

const file_api_protocol_proto_rawDesc = "" +
	"\n" +
	"\x12api/protocol.proto\x12\x06lesson\";\n" +
	"\rNumberRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"U\n" +
	"\vNumberReply\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x03R\x06number\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node2D\n" +
	"\vApplication\x125\n" +
	"\aPropose\x12\x15.lesson.NumberRequest\x1a\x13.lesson.NumberReply2B\n" +
	"\vReplication\x123\n" +
	"\x05Apply\x12\x15.lesson.NumberRequest\x1a\x13.lesson.NumberReplyB\x16Z\x14lesson/broadcast/apib\x06proto3"

var (
	file_api_protocol_proto_rawDescOnce sync.Once
	file_api_protocol_proto_rawDescData []byte
)

func file_api_protocol_proto_rawDescGZIP() []byte {
	file_api_protocol_proto_rawDescOnce.Do(func() {
		file_api_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protocol_proto_rawDesc), len(file_api_protocol_proto_rawDesc)))
	})
	return file_api_protocol_proto_rawDescData
}

var file_api_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_protocol_proto_goTypes = []any{
	(*NumberRequest)(nil), // 0: lesson.NumberRequest
	(*NumberReply)(nil),   // 1: lesson.NumberReply
}
var file_api_protocol_proto_depIdxs = []int32{
	0, // 0: lesson.Application.Propose:input_type -> lesson.NumberRequest
	0, // 1: lesson.Replication.Apply:input_type -> lesson.NumberRequest
	1, // 2: lesson.Application.Propose:output_type -> lesson.NumberReply
	1, // 3: lesson.Replication.Apply:output_type -> lesson.NumberReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protocol_proto_init() }
func file_api_protocol_proto_init() {
	if File_api_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protocol_proto_rawDesc), len(file_api_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_protocol_proto_goTypes,
		DependencyIndexes: file_api_protocol_proto_depIdxs,
		MessageInfos:      file_api_protocol_proto_msgTypes,
	}.Build()
	File_api_protocol_proto = out.File
	file_api_protocol_proto_goTypes = nil
	file_api_protocol_proto_depIdxs = nil
}
